version: "3"
services:
  server:  # This is the service name
    container_name: server
    build:
      context: .  # Specify the Docker build context (usually '.')
      dockerfile: Dockerfile
    ports:
      - 5555:5000
